---
# Role tasks

- name: Setup interactive mode on initd systems
  include_tasks: init.yml
  when: ansible_facts.distribution_major_version is version("7", "<")
  tags:
    - role::interactive_mode
    - role::interactive_mode::initd

- name: Setup interactive mode on initd systems
  include_tasks: systemd.yml
  when: ansible_facts.distribution_major_version is version("7", ">=")
  tags:
    - role::interactive_mode
    - role::interactive_mode::systemd
