---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check interactive startup
      shell: grep --fixed-strings "{{ item }}" /etc/sysconfig/init
      changed_when: no
      loop:
        - 'PROMPT=no'
